### ISSUE TITLE
new_version_plus 0.0.12: package does not exist, or is not a plugin 

### ISSUE THREAD

**Issue by sonali9421** [CodesFirst/new_version_plus#68]
Package new_version_plus:android references com.codesfirst.new_version_plus:android as the default plugin, but the package does not exist, or is not a plugin package.
Ask the maintainers of new_version_plus to either avoid referencing a default implementation via `platforms: android: default_package: com.codesfirst.new_version_plus` or create a plugin named com.codesfirst.new_version_plus.

Package new_version_plus:ios references com.codesfirst.new_version_plus:ios as the default plugin, but the package does not exist, or is not a plugin package.
Ask the maintainers of new_version_plus to either avoid referencing a default implementation via `platforms: ios: default_package: com.codesfirst.new_version_plus` or create a plugin named com.codesfirst.new_version_plus.

**Comment by leonardoayres** [comment]
Hello all,

To fix this I've just removed the following lines from pubspec.yaml:

```
flutter:
  plugin:
    platforms:
      android:
        package: com.codesfirst.new_version_plus
        pluginClass: new_version_plus        
      ios:        
        pluginClass: new_version_plus 
```
After this I was able to compile and debug my app.
